name: tests unitaires
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
      - name: install
        run: pip install pytest
      - name: Run tests
        run: pytest TP1/test.py
      - name: Nom branche
        run: echo "Nom de la branche :"
        run: echo ${{ github.ref }}
      - name: VM OS
        run: echo "Système d'exploitation de la VM :"
        run: echo ${{ runner.os }}
